PONTTO_Z_OFFSET = 210
PONTTO_X_OFFSET = 57.5
PONTTO_ARM_LENGTH = 835
PONTTO_MOTOR_MIN_ANGLE = -172

PAATY_X_OFFSET = 105
PAATY_ARM_LENGTH = 905

BASE_X_OFFSET = 920
BASE_Y_OFFSET = -240
BASE_Z_OFFSET = 0

BASE_TRANSFORM_MATRIX = [[1, 0, 0, BASE_X_OFFSET], 
                         [0, 1, 0, BASE_Y_OFFSET], 
                         [0, 0, 1, BASE_Z_OFFSET], 
                         [0, 0, 0, 1]]

RAIL_ANGLE = 137.6

THETA_2_VAL_IN_INIT = 90 + 73.17
DELTA_R_VAL_IN_INIT = 0.0

RAIL_MIN_LIMIT = -0.1   # This is basically zero, but to allow -0 value to pass it's nto actually zero
RAIL_MAX_LIMIT = 731.3
SCREW_DRIVE_PITCH = 10.0

PONTTO_MOTOR_PULSE_PIN = 13
PONTTO_MOTOR_DIR_PIN = 26
PONTTO_MOTOR_SENSOR_PIN = 22
PONTTO_MOTOR_GEAR_RATION = 5*32/10

PAATY_MOTOR_PULSE_PIN = 20
PAATY_MOTOR_DIR_PIN = 19
PAATY_MOTOR_SENSOR_PIN = 23
PAATY_MOTOR_GEAR_RATIO = 5

RAIL_MOTOR_PULSE_PIN = 27
RAIL_MOTOR_DIR_PIN = 4
RAIL_MOTOR_SENSOR_PIN = 24
RAIL_MOTOR_GEAR_RATIO = 1

MOTORS_MIN_DELAY = 1e-4
MOTORS_MAX_DELAY= 1e-3

FAN_PIN = 18
MIN_TEMP_IN_BOX = 30.0
MAX_TEMP_IN_BOX = 60.0

SAFE_ZONE_Y_CORD = 1200
SAFE_ZONE_X_CORD = -1100